mybatis.config-locations: classpath:mybatis.xml
mybatis.mapper-locations: classpath:mapper/*.xml

spring.datasource.url: jdbc:mysql://45.61.238.182:3306/zb_task?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: qvod
spring.datasource.password: fe624bdc97a31
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

logging.level.root: INFO
logging.level.org.springframework.web: WARN
logging.level.com.eason: INFO


spring.data.mongodb.uri:  mongodb://qvod:PGJ1AoZIQViooc0n@45.61.238.182:7081/qvod

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis.database:  0
spring.redis.database10:  10
# Redis服务器地址
spring.redis.host:  45.61.238.182
# Redis服务器连接端口
spring.redis.port:  6378
# Redis服务器连接密码（默认为空）
spring.redis.password:  778092c2cd71661098ff920af0feb89a
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 0
#TestOnBorrow设置为false，导致有时获取的连接不可用
spring.redis.testOnBorrow:  false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8771/eureka/
server:
  port: 8775
  tomcat:
        uri-encoding: UTF-8


spring:
  application:
    name: service-api-user-impl
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb

user:
  file:
      img:
        local:  /data/img/
#        local:  D:/img/
        remote: http://img.qstuanwei.com/data/img/
