endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

logging.level.root: ERROR
logging.level.org.springframework: INFO
logging.level.com.eason: ERROR


eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
server:
    port: 8777
spring:
    application:
        name: zb-live-media

spring.datasource.url: jdbc:mysql://45.61.238.182:3306/zb?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: qvod
spring.datasource.password: fe624bdc97a31
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.data.mongodb.uri:  mongodb://qvod:PGJ1AoZIQViooc0n@45.61.238.182:7081/qvod

platfrom:
    tencent:
        producer: https://cloud.tencent.com
        key: 35844ae13af61b76e4dd1bf0517cb2dc
        appid: 1255349331
        bizid: 23450
        appName: live
        line: r2
        pushUrl:
            r1:  rtmp://%1$s.livepush.myqcloud.com/live/%2$s
            r2: http://%1$s.livepush.myqcloud.com/live/%2$s.flv
            r3: http://%1$s.livepush.myqcloud.com/live/%2$s.m3u8
        playUrl:
            r1:  rtmp://%1$s.liveplay.myqcloud.com/live/%2$s
            r2: http://%1$s.liveplay.myqcloud.com/live/%2$s.flv
            r3: http://%1$s.liveplay.myqcloud.com/live/%2$s.m3u8
    jsy:
            producer: https://kls.ksyun.com
            appName: live
            line: r1
            pushUrl:
                r1:  rtmp://rtmp.xzjcn.com/live/%1$s
                r2:  rtmp://push.xzjcn.com/live/%1$s
            playUrl:
                r1:  http://down.xzjcn.com/live/%1$s/index.m3u8
                r2:  rtmp://pull.xzjcn.com/live/%1$s
    dnion:
            producer: https://portal.dnion.com
            appName: xclive
            line: r1
            pushUrl:
                r1:  rtmp://720113.com/xclive/%1$s
            playUrl:
                r1:  http://dtxishuimo.com/xclive/%1$s.flv
